### ISSUE TITLE
慈禧全传

### ISSUE THREAD

**Issue by hH-yY-xX** [hH-yY-xX/books#2]
作者：高阳
出版社：新星出版社
阅读方式：纸质书/微信读书
开始：2022.4.24
购买方式：京东

**Comment by william-hyx** [comment]
第一卷 慈禧前传
开始：2024.7.24

**Comment by hH-yY-xX** [comment]
慈禧作为一位政治人物，个人能力毋庸置疑是合格的。但是个人的私欲牢牢凌驾于统治利益，统治利益又凌驾于国家利益，所以中后期的很多操作都是为了巩固个人权力，巩固亲贵宗室的利益。人事安排上选择了很多亲贵宗室没有能力、易于掌控的人掌握重要权力，当这些选上的人做大，可能出现威胁她的权力时又会安排新的人进行权力格局再平衡。
